### ISSUE TITLE
outdated podspec

### ISSUE THREAD

**Issue by pteasima** [Vaultio/EtherKit#15]
Hey guys, Petr from Ackee. We've started experimenting with EtherKit. We can see that its still in active development (public API changing and what not), so we wanna give you time and space to finish it. Thus, I'll be just making issues with suggestions and feature requests atm, deal with them however you like. We might contribute some code at later stages, when the codebase is more stable. We'll try to focus as much as possible on our task (ABI codegen) and connect it to EtherKit later.

**Outdated podspec**
The podspec in master branch declares version 0.1.4, but still points to the 0.1.3 tag in git. Please consider pointing it to HEAD of master branch to make the latest code available for people who choose to use this podspec directly (not the one from shared cocoapods repo)

**Comment by pr0zac** [comment]
Acknowledged! Thanks @pteasima!

**Comment by pr0zac** [comment]
Should be updated now!
