### ISSUE TITLE
cant call functions with long String parameters

### ISSUE THREAD

**Issue by pteasima** [Vaultio/EtherKit#28]
Hey guys, we tried calling a smartContract function with a single string parameter using the snippet below.

```
// I have a HelloWorld contract running at this address, it has the following ABI:
      // [ { "constant": false, "inputs": [ { "name": "message", "type": "string" } ], "name": "say", "outputs": [ { "name": "result", "type": "string" } ], "payable": true, "stateMutability": "payable", "type": "function" }, { "inputs": [], "payable": false, "stateMutability": "nonpayable", "type": "constructor" } ]
      // We want to be able to call its "say" function with a String parameter. It should return a String.
      let helloWorldContractAddress = try! Address(describing: "0xB613F40d3f055F2DebA3cc498Ec83d54778134Ca")
      let sayHiFunctionCall = Function(name: "say", parameters: ["Hey"])
      let sayHiData = GeneralData(data: sayHiFunctionCall.encodeToCall())
      query.send(using: keyManager, from: myAddress, to: helloWorldContractAddress, value: UInt256(0x031c00000000000), data: sayHiData) { result in
        switch result {
        case let .failure(error):
          self.showError(error.localizedDescription)
        case let .success(value):
          print(value)
        }
      }
```

`estimatedGasPrice` gives the following error:

```
▿ 0 : 2 elements
          - key : message
          - value : gas required exceeds allowance or always failing transaction
        ▿ 1 : 2 elements
          - key : code
          - value : -32000
```

Ive narrowed down the problem, and it appears that if I pass any string of length `<= 2` , i.e. for example the "Hi", it does work. If I pass any string 3 characters or longer (e.g. "Hey" from the above example), it fails with the above error. 

Data serialized by EtherKit:
`0xd5c6130100000000000000000000000000000000000000000000000000000000000000034865790000000000000000000000000000000000000000000000000000000000`
Data serialized by the official Ethereum wallet when making the same call, which works:
`0xd5c61301000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000034865790000000000000000000000000000000000000000000000000000000000`

Clearly the Ethereum Wallet produces more zeros and an extra `2` :D 

Let us know if we can provide any further info. Thanks, Petr from Ackee

**Comment by pr0zac** [comment]
Well thats weird. Strings are one of the areas I thought I'd tested the most. I'll look into this this afternoon. Thanks @pteasima

**Comment by SirensOfTitan** [comment]
@pr0zac: Did you ever get a chance to look at this?

**Comment by pr0zac** [comment]
I didn't have a chance because of launch prep stuff. Gonna start looking now.

**Comment by pr0zac** [comment]
Looks like there was a problem with how I encode dynamic types for function calls. I believe I've fixed this, it should work correctly in master now.
